### ISSUE TITLE
Error when I run bin\instance fg

### ISSUE THREAD

**Issue by LeuAlmeida** [plone/simple-plone-buildout#11]
I started a Plone project through buildout, however, when I run `bin\instance fg`, I get a message in cmd stating that the command is not valid. 

I didn't find this issue here, so I decided to open a new one.

Thanksss!

**Comment by jugmac00** [comment]
Hi @LeuAlmeida 

it would be very helpful if you both provide the error message and which instruction you followed (buildout).

Thank you!

**Comment by LeuAlmeida** [comment]
Hi @jugmac00 , thanks for your help.

I got this error:
```
An error occurred when trying to install c:\users\leonar~1.alm\appdata\local\temp\tmpecjqcfget_dist\plone.staticresources-1.1.0.tar.gz. Look above this message for any errors that were output by easy_install.
While:
  Installing instance.
  Getting distribution for 'plone.staticresources==1.1.0'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "c:\plonecms\buildout\env\lib\site-packages\zc\buildout\buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "c:\plonecms\buildout\env\lib\site-packages\zc\buildout\buildout.py", line 817, in install
    installed_files = self[part]._call(recipe.install)
  File "c:\plonecms\buildout\env\lib\site-packages\zc\buildout\buildout.py", line 1603, in _call
    return f()
  File "c:\plonecms\buildout\eggs\plone.recipe.zope2instance-6.3.0-py2.7.egg\plone\recipe\zope2instance\recipe.py", line 145, in install
    installed.extend(self.install_scripts())
  File "c:\plonecms\buildout\eggs\plone.recipe.zope2instance-6.3.0-py2.7.egg\plone\recipe\zope2instance\recipe.py", line 782, in install_scripts
    requirements, ws = self.egg.working_set(['plone.recipe.zope2instance'])
  File "c:\plonecms\buildout\eggs\zc.recipe.egg-2.0.7-py2.7.egg\zc\recipe\egg\egg.py", line 87, in working_set
    allow_unknown_extras=bool_option(buildout_section, 'allow-unknown-extras')
  File "c:\plonecms\buildout\eggs\zc.recipe.egg-2.0.7-py2.7.egg\zc\recipe\egg\egg.py", line 168, in _working_set
    allow_unknown_extras=allow_unknown_extras)
  File "c:\plonecms\buildout\env\lib\site-packages\zc\buildout\easy_install.py", line 957, in install
    return installer.install(specs, working_set)
  File "c:\plonecms\buildout\env\lib\site-packages\zc\buildout\easy_install.py", line 730, in install
    for dist in self._get_dist(req, ws):
  File "c:\plonecms\buildout\env\lib\site-packages\zc\buildout\easy_install.py", line 574, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "c:\plonecms\buildout\env\lib\site-packages\zc\buildout\easy_install.py", line 1745, in _move_to_eggs_dir_and_compile
    [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
ValueError: need more than 0 values to unpack
```

**Comment by tkimnguyen** [comment]
Please use our support forum to ask for help. https://community.plone.org.

**Comment by tkimnguyen** [comment]
Your question thread was started by @jugmac00 at https://community.plone.org/t/problem-with-simple-plone-buildout/10354/2?u=tkimnguyen so please go there, create an account, and we can follow up in that thread.

**Comment by LeuAlmeida** [comment]
Hello @tkimnguyen ,

I solved my problem after i was migrated to LInux. Here i had 0 problems :)

Thanks for your help!
