### ISSUE TITLE
errors when almost last step - running env/Scripts/buildout for windows

### ISSUE THREAD

**Issue by ghost** [plone/simple-plone-buildout#12]
hi,
whatever i ran env/Scripts/buildout -Nv or env/Scripts/buildout 
at the end i got the same errors:

could anyone give a hint? or i must install Plone 4.3 to my win7. I need Plone 5 for new job.
Many thanks.

warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*' found under directory 'news'
warning: no previously-included files found matching 'news'
error: Setup script exited with error: SandboxViolation: open('build\\lib\\plone\\staticresources\\static\\components\\cs-jqtree-contextmenu\\node_modules\\jqtree\\static\\bower_components\\fontawesome\\web-fonts-with-css\\webfonts\\fa-brands-400.woff2', 'wb') {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

An error occurred when trying to install c:\users\viktorie\appdata\local\temp\tmp8sb2jdget_dist\plone.staticresources-1.1.0.tar.gz. Look above this message for any errors that were output by easy_install.
While:
  Installing instance.
  Getting distribution for 'plone.staticresources==1.1.0'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "c:\simple-plone-buildout\env\lib\site-packages\zc\buildout\buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "c:\simple-plone-buildout\env\lib\site-packages\zc\buildout\buildout.py", line 817, in install
    installed_files = self[part]._call(recipe.install)
  File "c:\simple-plone-buildout\env\lib\site-packages\zc\buildout\buildout.py", line 1603, in _call
    return f()
  File "c:\simple-plone-buildout\eggs\plone.recipe.zope2instance-6.3.0-py2.7.egg\plone\recipe\zope2instance\recipe.py", line 145, in install
    installed.extend(self.install_scripts())
  File "c:\simple-plone-buildout\eggs\plone.recipe.zope2instance-6.3.0-py2.7.egg\plone\recipe\zope2instance\recipe.py", line 782, in install_scripts
    requirements, ws = self.egg.working_set(['plone.recipe.zope2instance'])
  File "c:\simple-plone-buildout\eggs\zc.recipe.egg-2.0.7-py2.7.egg\zc\recipe\egg\egg.py", line 87, in working_set
    allow_unknown_extras=bool_option(buildout_section, 'allow-unknown-extras')
  File "c:\simple-plone-buildout\eggs\zc.recipe.egg-2.0.7-py2.7.egg\zc\recipe\egg\egg.py", line 168, in _working_set
    allow_unknown_extras=allow_unknown_extras)
  File "c:\simple-plone-buildout\env\lib\site-packages\zc\buildout\easy_install.py", line 957, in install
    return installer.install(specs, working_set)
  File "c:\simple-plone-buildout\env\lib\site-packages\zc\buildout\easy_install.py", line 730, in install
    for dist in self._get_dist(req, ws):
  File "c:\simple-plone-buildout\env\lib\site-packages\zc\buildout\easy_install.py", line 574, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "c:\simple-plone-buildout\env\lib\site-packages\zc\buildout\easy_install.py", line 1745, in _move_to_eggs_dir_and_compile
    [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
ValueError: need more than 0 values to unpack

Viktorie@Viktorie-PC MINGW64 /c/simple-plone-buildout (master)

**Comment by tkimnguyen** [comment]
I'm getting the same on macOS 10.15.7. This is a recent problem for me. Looking into it...

**Comment by ataoleo** [comment]
在windows 下也出现同样的问题
While: 
Initializing. 
Error: Error downloading extends for URL http://dist.plone.org/release/5.0.8/ver 
sions.cfg: [Errno 10054] An existing connection was forcibly closed by the remot 
e host
